require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SimsInstrumentConfigurationsController do

  # This should return the minimal set of attributes required to create a valid
  # SimsInstrumentConfiguration. As you add validations to SimsInstrumentConfiguration, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all sims_instrument_configurations as @sims_instrument_configurations" do
      sims_instrument_configuration = SimsInstrumentConfiguration.create! valid_attributes
      get :index
      assigns(:sims_instrument_configurations).should eq([sims_instrument_configuration])
    end
  end

  describe "GET show" do
    it "assigns the requested sims_instrument_configuration as @sims_instrument_configuration" do
      sims_instrument_configuration = SimsInstrumentConfiguration.create! valid_attributes
      get :show, :id => sims_instrument_configuration.id.to_s
      assigns(:sims_instrument_configuration).should eq(sims_instrument_configuration)
    end
  end

  describe "GET new" do
    it "assigns a new sims_instrument_configuration as @sims_instrument_configuration" do
      get :new
      assigns(:sims_instrument_configuration).should be_a_new(SimsInstrumentConfiguration)
    end
  end

  describe "GET edit" do
    it "assigns the requested sims_instrument_configuration as @sims_instrument_configuration" do
      sims_instrument_configuration = SimsInstrumentConfiguration.create! valid_attributes
      get :edit, :id => sims_instrument_configuration.id.to_s
      assigns(:sims_instrument_configuration).should eq(sims_instrument_configuration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SimsInstrumentConfiguration" do
        expect {
          post :create, :sims_instrument_configuration => valid_attributes
        }.to change(SimsInstrumentConfiguration, :count).by(1)
      end

      it "assigns a newly created sims_instrument_configuration as @sims_instrument_configuration" do
        post :create, :sims_instrument_configuration => valid_attributes
        assigns(:sims_instrument_configuration).should be_a(SimsInstrumentConfiguration)
        assigns(:sims_instrument_configuration).should be_persisted
      end

      it "redirects to the created sims_instrument_configuration" do
        post :create, :sims_instrument_configuration => valid_attributes
        response.should redirect_to(SimsInstrumentConfiguration.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sims_instrument_configuration as @sims_instrument_configuration" do
        # Trigger the behavior that occurs when invalid params are submitted
        SimsInstrumentConfiguration.any_instance.stub(:save).and_return(false)
        post :create, :sims_instrument_configuration => {}
        assigns(:sims_instrument_configuration).should be_a_new(SimsInstrumentConfiguration)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SimsInstrumentConfiguration.any_instance.stub(:save).and_return(false)
        post :create, :sims_instrument_configuration => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sims_instrument_configuration" do
        sims_instrument_configuration = SimsInstrumentConfiguration.create! valid_attributes
        # Assuming there are no other sims_instrument_configurations in the database, this
        # specifies that the SimsInstrumentConfiguration created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SimsInstrumentConfiguration.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sims_instrument_configuration.id, :sims_instrument_configuration => {'these' => 'params'}
      end

      it "assigns the requested sims_instrument_configuration as @sims_instrument_configuration" do
        sims_instrument_configuration = SimsInstrumentConfiguration.create! valid_attributes
        put :update, :id => sims_instrument_configuration.id, :sims_instrument_configuration => valid_attributes
        assigns(:sims_instrument_configuration).should eq(sims_instrument_configuration)
      end

      it "redirects to the sims_instrument_configuration" do
        sims_instrument_configuration = SimsInstrumentConfiguration.create! valid_attributes
        put :update, :id => sims_instrument_configuration.id, :sims_instrument_configuration => valid_attributes
        response.should redirect_to(sims_instrument_configuration)
      end
    end

    describe "with invalid params" do
      it "assigns the sims_instrument_configuration as @sims_instrument_configuration" do
        sims_instrument_configuration = SimsInstrumentConfiguration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SimsInstrumentConfiguration.any_instance.stub(:save).and_return(false)
        put :update, :id => sims_instrument_configuration.id.to_s, :sims_instrument_configuration => {}
        assigns(:sims_instrument_configuration).should eq(sims_instrument_configuration)
      end

      it "re-renders the 'edit' template" do
        sims_instrument_configuration = SimsInstrumentConfiguration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SimsInstrumentConfiguration.any_instance.stub(:save).and_return(false)
        put :update, :id => sims_instrument_configuration.id.to_s, :sims_instrument_configuration => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sims_instrument_configuration" do
      sims_instrument_configuration = SimsInstrumentConfiguration.create! valid_attributes
      expect {
        delete :destroy, :id => sims_instrument_configuration.id.to_s
      }.to change(SimsInstrumentConfiguration, :count).by(-1)
    end

    it "redirects to the sims_instrument_configurations list" do
      sims_instrument_configuration = SimsInstrumentConfiguration.create! valid_attributes
      delete :destroy, :id => sims_instrument_configuration.id.to_s
      response.should redirect_to(sims_instrument_configurations_url)
    end
  end

end
